services:
  ark-dashboard:
    build: ./dashboard
    container_name: game-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "0:0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    environment:
      - DASHBOARD_PASSWORD_HASH=${DASHBOARD_PASSWORD_HASH}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DATA_DIR=/app/data
