[ServerSettings]
ServerPassword=6742
ServerAdminPassword=6742
RCONEnabled=True
RCONPort=27020
RCONServerGameLogBuffer=600
MaxPlayers=20
MapPlayerLocation=True
AllowThirdPersonPlayer=True
ShowFloatingDamageText=True
AllowHitMarkers=True

# Performance / QoL
MaxTamedDinos=4000
ServerAutoForceRespawnWildDinosInterval=86400

# Rates
TamingSpeedMultiplier=5.0
XPMultiplier=3.0
HarvestAmountMultiplier=3.0
HarvestHealthMultiplier=2.0
DinoCharacterFoodDrainMultiplier=0.5
PlayerCharacterFoodDrainMultiplier=0.5
PlayerCharacterWaterDrainMultiplier=0.5
PlayerCharacterStaminaDrainMultiplier=0.5
DinoCharacterStaminaDrainMultiplier=0.5
ResourcesRespawnPeriodMultiplier=0.5

# Breeding
BabyMatureSpeedMultiplier=10.0
EggHatchSpeedMultiplier=10.0
MatingIntervalMultiplier=0.1
BabyCuddleIntervalMultiplier=0.1
BabyImprintAmountMultiplier=3.0

# Day/Night
DayTimeSpeedScale=0.5
NightTimeSpeedScale=2.0
DayCycleSpeedScale=0.5

# Engrams
bAutoUnlockAllEngrams=True

# Stack & Weight
PerPlatformMaxStructuresMultiplier=2.0
ItemStackSizeMultiplier=5.0

[SessionSettings]
SessionName=HidiARK
QueryPort=27015
Port=7777
MultiHome=0.0.0.0

[MessageOfTheDay]
Message=환영합니다! HidiARK 서버에 오신 것을 환영합니다.
Duration=20

[/Script/ShooterGame.ShooterGameMode]
bDisableStructurePlacementCollision=True
MaxNumberOfPlayersInTribe=10
BabyImprintingStatScaleMultiplier=1.0
